version: '3'

services:
    dynamodb_local:
        command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data -cors http://localhost:5000"
        image: "amazon/dynamodb-local:latest"
        container_name: dynamodb_local
        ports:
            - "4200:8000"
        volumes:
            - ".:/home/dynamodblocal/data"
        working_dir:  /home/dynamodblocal
        environment:
            AWS_ACCESS_KEY_ID: DUMMY_ID
            AWS_SECRET_ACCESS_KEY: DUMMY_KEY
            REGION: 'us-west-2'
# lembrar de ler a pasta docs/tutorial aqui no root para exportar as variaveis
    dynamodb_manager:
        container_name: manager
        image: taydy/dynamodb-manager
        privileged: true
        restart: always
        depends_on:
            - dynamodb_local
        ports:
            - "5000:80"
    redis:
        container_name: redis
        image: redis
        ports:
          - 6379:6379