version: '3'

services:
    dynamodb:
        image: amazon/dynamodb-local:1.21.0
        container_name: dynamodb
        hostname: dynamodb
        restart: always
        volumes:
            - .:/home/dynamodblocal/data
            - /etc/localtime:/etc/localtime:ro
        ports:
            - ${DYNAMO_DB_PORT:-4200}:8000
        command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
        # lembrar de ler a pasta docs/tutorial aqui no root para exportar as variaveis
    
    dynamodb-admin:
        image: aaronshaf/dynamodb-admin
        container_name: dynamodb-admin
        ports:
            - 8200:8001
        environment:
            DYNAMO_ENDPOINT: http://dynamodb:8000
            AWS_REGION: local
            AWS_ACCESS_KEY_ID: local
            AWS_SECRET_ACCESS_KEY: local
        depends_on:
            - dynamodb

    redis:
        container_name: redis
        image: redis
        ports:
          - 6379:6379